apiVersion: v2
name: fleet-monitor
version: 0.0.0
appVersion: 0.0.0
description: Fleet Monitor - Read-only monitoring for Fleet controllers
icon: https://charts.rancher.io/assets/logos/fleet.svg
annotations:
  catalog.cattle.io/namespace: cattle-fleet-system
  catalog.cattle.io/kube-version: '>= 1.28.0-0 < 1.33.0-0'
